---
title: "Basics about arules package"
output: html_notebook
---

```{r}
# Loading arules package into R
library("arules")
# Loading Epub data
data("Epub")
Epub
# Get summary of Epub
summary(Epub)
```

```{r}
# Get available years in transaction data
year <- strftime(as.POSIXlt(transactionInfo(Epub)[["TimeStamp"]]), "%Y")
# Table counting number of appearance of each year in transaction data
table(year)
```

```{r}
# Extract Epub data for year 2003
Epub2003 <- Epub[year == "2003"]
length(Epub2003)
```

```{r}
image(Epub2003)
```

```{r}
# Get data frame of transaction info for transactions having more than 20 items in 2003
transactionInfo(Epub2003[size(Epub2003) > 20])
# Get more information (item lists) in transactions having more than 20 items in 2003
inspect(Epub2003[size(Epub2003) > 20])
```

```{r}
# Get information about first 5 transactions in 2003
inspect(Epub2003[1:5])
```

```{r}
# Coerce first 5 transactions(?) in Epub2003 to list class
EpubList = as(Epub2003[1:5], "list")
EpubList
```


```{r}
# Coerce Epub database into tidLists class
# Each list in tidLists contains the transaction IDs for an item (the support is given by the length of the list)
EpubTidLists <- as(Epub, "tidLists")
EpubTidLists
# Length of EpubTidLists
length(EpubTidLists)
```

```{r}
# Coerce first three items in EpubTidLists to list class
as(EpubTidLists[1:3], "list")
```

```{r}
# Draw frequency of items having relative support of at least 0.01
itemFrequencyPlot(Epub, support = 0.01, cex.names = 0.8) # cex.names is for font size of bar labels
```

```{r}
# Apply apriori algorithm to find association rules with min_sup = 0.001 and min_conf = 0.6
rules <- apriori(Epub, parameter = list(support = 0.001, confidence = 0.6))
```

```{r}
# Get summary about generated rules
summary(rules)
```

```{r}
# Get information of each generated rules
inspect(rules)
```


```{r}
# Get information of 3 rules having highest lift
inspect(head(sort(rules, by = "lift"), n = 3))
```

```{r}
# Get subrules with confidence > 0.7
subrules <- rules[quality(rules)$confidence > 0.7]
# Get summary of subrules
summary(subrules)
```
```{r}
# Get information of subrules
inspect(subrules)
```

