---
title: "R Notebook"
output: html_notebook
---


```{r}
iris2 <- iris
iris2$Species <- NULL
(kmeans.result <- kmeans(iris2, 3))
```

```{r}
table(iris$Species, kmeans.result$cluster)
```

```{r}
plot(iris2[c("Sepal.Length", "Sepal.Width")], col = kmeans.result$cluster)
# plot cluster centers
points(kmeans.result$centers[,c("Sepal.Length", "Sepal.Width")], col = 1:3, pch = 8, cex =2)
```

```{r}
library(fpc)
pamk.result <- pamk(iris2)
# number of clusters
pamk.result$nc
```

```{r}
# check clustering against actual species
table(pamk.result$pamobject$clustering, iris$Species)
```

```{r}
layout(matrix(c(1,2),1,2)) # 2 graphs per page
plot(pamk.result$pamobject)
layout(matrix(1)) # change back to one graph per page
```

```{r}
library(cluster)
pam.result <- pam(iris2, 3) # PAM
table(pam.result$clustering, iris$Species)
```

```{r}
layout(matrix(c(1,2), 1, 2)) # 2 graphs per page
```

```{r}
plot(pam.result)
layout(matrix(1)) # change back to 1 graph per page
```

```{r}
# Dendrogram graph
idx <- sample(1:dim(iris)[1], 40)
irisSample <- iris[idx,]
irisSample$Species <- NULL
hc <- hclust(dist(irisSample), method="ave")
plot(hc, hang = -1, labels=iris$Species[idx])
# cut tree into 3 clusters
rect.hclust(hc, k=3)
groups <- cutree(hc, k=3)
```


```{r}
library(fpc)
iris2 <- iris[-5]
ds <- dbscan(iris2, eps = 0.42, MinPts=5)
# compare clusters with original class labels
table(ds$cluster, iris$Species)
```

```{r}
plot(ds, iris2)
plot(ds, iris2[c(1,4)])
plotcluster(iris2, ds$cluster)
```



